"""initial schema

Revision ID: b2f2da3c7b47
Revises: 
Create Date: 2026-03-26 19:05:30.600675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f2da3c7b47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('heart_rate_resting', sa.Integer(), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_min', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_data_user_id'), 'activity_data', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('was_read', sa.Boolean(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('glucose_at_alert', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('glucose_avg', sa.Float(), nullable=True),
    sa.Column('glucose_min', sa.Float(), nullable=True),
    sa.Column('glucose_max', sa.Float(), nullable=True),
    sa.Column('time_in_range_pct', sa.Float(), nullable=True),
    sa.Column('time_below_range_pct', sa.Float(), nullable=True),
    sa.Column('time_above_range_pct', sa.Float(), nullable=True),
    sa.Column('crash_count', sa.Integer(), nullable=True),
    sa.Column('spike_count', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_active_calories', sa.Integer(), nullable=True),
    sa.Column('workout_minutes', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('meals_logged', sa.Integer(), nullable=True),
    sa.Column('glucose_score', sa.Integer(), nullable=True),
    sa.Column('nutrition_score', sa.Integer(), nullable=True),
    sa.Column('activity_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_summary_user_date')
    )
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.create_table('food_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=True),
    sa.Column('food_category', sa.String(length=50), nullable=True),
    sa.Column('avg_peak_glucose', sa.Float(), nullable=True),
    sa.Column('avg_time_to_peak_min', sa.Integer(), nullable=True),
    sa.Column('avg_time_to_baseline_min', sa.Integer(), nullable=True),
    sa.Column('crash_probability', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('last_eaten', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_responses_user_id'), 'food_responses', ['user_id'], unique=False)
    op.create_table('glucose_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('glucose_mmol', sa.Float(), nullable=False),
    sa.Column('trend_arrow', sa.Integer(), nullable=True),
    sa.Column('is_high', sa.Boolean(), nullable=False),
    sa.Column('is_low', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_readings_timestamp'), 'glucose_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_glucose_readings_user_id'), 'glucose_readings', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('avg_gi_score', sa.String(length=10), nullable=True),
    sa.Column('predicted_spike', sa.Float(), nullable=True),
    sa.Column('actual_peak', sa.Float(), nullable=True),
    sa.Column('actual_peak_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('hba1c_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=True),
    sa.Column('daily_protein_target_g', sa.Integer(), nullable=True),
    sa.Column('glucose_low_threshold', sa.Float(), nullable=False),
    sa.Column('glucose_high_threshold', sa.Float(), nullable=False),
    sa.Column('glucose_target_low', sa.Float(), nullable=False),
    sa.Column('glucose_target_high', sa.Float(), nullable=False),
    sa.Column('preferred_channel', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('libre_auth_token', sa.String(), nullable=True),
    sa.Column('libre_patient_id', sa.String(length=50), nullable=True),
    sa.Column('garmin_oauth_token', sa.String(), nullable=True),
    sa.Column('garmin_oauth_secret', sa.String(), nullable=True),
    sa.Column('metabolic_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('workouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('glucose_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('glucose_value', sa.Float(), nullable=True),
    sa.Column('trigger_meal_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('was_predicted', sa.Boolean(), nullable=False),
    sa.Column('was_alerted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trigger_activity_id'], ['workouts.id'], ),
    sa.ForeignKeyConstraint(['trigger_meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_events_user_id'), 'glucose_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glucose_events_user_id'), table_name='glucose_events')
    op.drop_table('glucose_events')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('users')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_glucose_readings_user_id'), table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_timestamp'), table_name='glucose_readings')
    op.drop_table('glucose_readings')
    op.drop_index(op.f('ix_food_responses_user_id'), table_name='food_responses')
    op.drop_table('food_responses')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_activity_data_user_id'), table_name='activity_data')
    op.drop_table('activity_data')
    # ### end Alembic commands ###
