"""add focus system and user memory tables

Revision ID: be7af176c7e7
Revises: b2f2da3c7b47
Create Date: 2026-03-29 13:48:40.930451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7af176c7e7'
down_revision: Union[str, None] = 'b2f2da3c7b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_focus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ritual_shower', sa.Boolean(), nullable=False),
    sa.Column('ritual_real_clothes', sa.Boolean(), nullable=False),
    sa.Column('ritual_face_ice', sa.Boolean(), nullable=False),
    sa.Column('ritual_phone_away', sa.Boolean(), nullable=False),
    sa.Column('ritual_one_thing_set', sa.Boolean(), nullable=False),
    sa.Column('ritual_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('one_thing', sa.Text(), nullable=True),
    sa.Column('one_thing_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('one_thing_done', sa.Boolean(), nullable=False),
    sa.Column('one_thing_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_pickups', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Text(), nullable=True),
    sa.Column('daily_win', sa.Text(), nullable=True),
    sa.Column('daily_win_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('energy_rating', sa.Integer(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_daily_focus_date'), 'daily_focus', ['date'], unique=False)
    op.create_index(op.f('ix_daily_focus_user_id'), 'daily_focus', ['user_id'], unique=False)
    op.create_table('focus_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_focus_id', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_blocks_user_id'), 'focus_blocks', ['user_id'], unique=False)
    op.create_table('focus_weekly_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('ritual_completion_days', sa.Integer(), nullable=True),
    sa.Column('focus_blocks_completed', sa.Integer(), nullable=True),
    sa.Column('one_thing_completed_days', sa.Integer(), nullable=True),
    sa.Column('avg_phone_pickups', sa.Float(), nullable=True),
    sa.Column('ideas_parked', sa.Integer(), nullable=True),
    sa.Column('total_focus_minutes', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_weekly_summaries_user_id'), 'focus_weekly_summaries', ['user_id'], unique=False)
    op.create_table('parked_ideas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parked_ideas_user_id'), 'parked_ideas', ['user_id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_focus_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_for_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_user_id'), 'todo_items', ['user_id'], unique=False)
    op.create_table('tune_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tune_requests_user_id'), 'tune_requests', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_category'), 'user_memories', ['category'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_category'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_tune_requests_user_id'), table_name='tune_requests')
    op.drop_table('tune_requests')
    op.drop_index(op.f('ix_todo_items_user_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_parked_ideas_user_id'), table_name='parked_ideas')
    op.drop_table('parked_ideas')
    op.drop_index(op.f('ix_focus_weekly_summaries_user_id'), table_name='focus_weekly_summaries')
    op.drop_table('focus_weekly_summaries')
    op.drop_index(op.f('ix_focus_blocks_user_id'), table_name='focus_blocks')
    op.drop_table('focus_blocks')
    op.drop_index(op.f('ix_daily_focus_user_id'), table_name='daily_focus')
    op.drop_index(op.f('ix_daily_focus_date'), table_name='daily_focus')
    op.drop_table('daily_focus')
    # ### end Alembic commands ###
